INSERT INTO `PRODUCT` (`NAME`, `QUANTITY`, `DESCRIPTION`, `IMAGE`) VALUES ('TOLL', 10, '*leiras*', 'pen.jpg');
INSERT INTO `PRODUCT` (`NAME`, `QUANTITY`, `DESCRIPTION`, `IMAGE`) VALUES ('CERUZA', 50, '*leiras*', 'pencil.jpg');

INSERT INTO `USER` (`NAME`, `EMAIL`, `USER_NAME`, `PASSWORD`, `ROLE`) VALUES ('admin', 'abcdc@gmail.hu', 'admin', '$2a$10$lW9Q6thFdccwPiRyOmQmreEtNhERoYGEsYKRL3uV97Q9u2ZGKxusW', 'ROLE_ADMIN');
INSERT INTO `USER` (`NAME`, `EMAIL`, `USER_NAME`, `PASSWORD`, `ROLE`) VALUES ('Gabor', 'elte@gmail.hu', 'felh', '$2a$10$lW9Q6thFdccwPiRyOmQmreEtNhERoYGEsYKRL3uV97Q9u2ZGKxusW', 'ROLE_USER');

INSERT INTO `TAG` (`TEXT`) VALUES ('akcios');
INSERT INTO `TAG` (`TEXT`) VALUES ('iroszer');

INSERT INTO `PRODUCT_TAGS` (`PRODUCTS_ID`, `TAGS_ID`) VALUES (1,1);
INSERT INTO `PRODUCT_TAGS` (`PRODUCTS_ID`, `TAGS_ID`) VALUES (1,2);