INSERT INTO `PRODUCT` (`NAME`, `QUANTITY`, `DESCRIPTION`) VALUES ('TOLL', 10, 'ASD');
INSERT INTO `PRODUCT` (`NAME`, `QUANTITY`, `DESCRIPTION`) VALUES ('CERUZA', 10, 'SDF');
INSERT INTO `PRODUCT` (`NAME`, `QUANTITY`, `DESCRIPTION`) VALUES ('PAPIR A4', 1000, 'DFG');
INSERT INTO `PRODUCT` (`NAME`, `QUANTITY`, `DESCRIPTION`) VALUES ('POSTIT', 1, 'QWE');

INSERT INTO `USER` (`NAME`, `EMAIL`, `USER_NAME`, `PASSWORD`, `LAST_LOGIN`, `ROLE`) VALUES ('admin', 'abcdc@gmail.hu', 'admin', '$2a$10$lW9Q6thFdccwPiRyOmQmreEtNhERoYGEsYKRL3uV97Q9u2ZGKxusW', null, 'ROLE_ADMIN');
INSERT INTO `USER` (`NAME`, `EMAIL`, `USER_NAME`, `PASSWORD`, `LAST_LOGIN`, `ROLE`) VALUES ('felhasznalo', 'elte@gmail.hu', 'felh', '$2a$10$lW9Q6thFdccwPiRyOmQmreEtNhERoYGEsYKRL3uV97Q9u2ZGKxusW', null, 'ROLE_USER');

INSERT INTO `RESERVATION` (`USERID`) VALUES (1);
INSERT INTO `RESERVATION` (`USERID`) VALUES (1);
INSERT INTO `RESERVATION` (`USERID`) VALUES (3);

INSERT INTO `TAG` (`TEXT`) VALUES ('IROSZER');
INSERT INTO `TAG` (`TEXT`) VALUES ('PAPIRARU');
INSERT INTO `TAG` (`TEXT`) VALUES ('AKCIO');

INSERT INTO `PRODUCT_TAGS` (`PRODUCTS_ID`, `TAGS_ID`) VALUES (1,1);
INSERT INTO `PRODUCT_TAGS` (`PRODUCTS_ID`, `TAGS_ID`) VALUES (1,3);
INSERT INTO `PRODUCT_TAGS` (`PRODUCTS_ID`, `TAGS_ID`) VALUES (2,1);
INSERT INTO `PRODUCT_TAGS` (`PRODUCTS_ID`, `TAGS_ID`) VALUES (3,2);
INSERT INTO `PRODUCT_TAGS` (`PRODUCTS_ID`, `TAGS_ID`) VALUES (4,2);

INSERT INTO `RESERVATION_PRODUCT` (`ORDERS_ID`, `PRODUCT_ID`) VALUES (1,1);
INSERT INTO `RESERVATION_PRODUCT` (`ORDERS_ID`, `PRODUCT_ID`) VALUES (1,2);
INSERT INTO `RESERVATION_PRODUCT` (`ORDERS_ID`, `PRODUCT_ID`) VALUES (1,3);

INSERT INTO `USER_RESERVATIONS` (`USER_ID`, `RESERVATIONS_ID`) VALUES (1,1);
INSERT INTO `USER_RESERVATIONS` (`USER_ID`, `RESERVATIONS_ID`) VALUES (1,2);
INSERT INTO `USER_RESERVATIONS` (`USER_ID`, `RESERVATIONS_ID`) VALUES (1,3);