INSERT INTO `PRODUCT` (`NAME`, `QUANTITY`, `DESCRIPTION`) VALUES ('TOLL', 10, 'ASD');
INSERT INTO `PRODUCT` (`NAME`, `QUANTITY`, `DESCRIPTION`) VALUES ('CERUZA', 10, 'SDF');
INSERT INTO `PRODUCT` (`NAME`, `QUANTITY`, `DESCRIPTION`) VALUES ('PAPIR A4', 1000, 'DFG');
INSERT INTO `PRODUCT` (`NAME`, `QUANTITY`, `DESCRIPTION`) VALUES ('POSTIT', 1, 'QWE');

INSERT INTO `ORDER` (`USERID`) VALUES (1);
INSERT INTO `ORDER` (`USERID`) VALUES (1);
INSERT INTO `ORDER` (`USERID`) VALUES (3);

INSERT INTO `TAG` (`TEXT`) VALUES ('IROESZKOZ');
INSERT INTO `TAG` (`TEXT`) VALUES ('PAPIRARU');

INSERT INTO ``
